name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        helm-version:
          - v3.11.0
          - v4.2.3

    name: CI (Helm ${{ matrix.helm-version }})

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true
          cache: true

      - uses: azure/setup-helm@v4
        with:
          version: ${{ matrix.helm-version }}

      - name: Run unit tests
        run: go test ./...

      - name: Run go vet
        run: go vet ./...

      - name: Install Helm Compose
        run: make install

      - name: Verify Helm Compose plugin
        run: helm plugin list

      - uses: helm/kind-action@v1.10.0
      
      - name: Run Helm Compose
        run: helm compose up -f examples/simple-compose.yaml

